# Generated by Django 4.2 on 2023-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitsong',
            name='values',
        ),
        migrations.AddField(
            model_name='splitsong',
            name='album',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splitsong',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
