# Generated by Django 4.2 on 2023-10-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_initial'),
        ('split', '0003_distributionreportpayment_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistributionReportPayment',
            new_name='SplitReportPayment',
        ),
    ]
