# Generated by Django 4.2 on 2023-10-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_rename_distributionreportpayment_splitreportpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitsong',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='split.split'),
        ),
    ]
