# Generated by Django 4.2 on 2023-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_alter_splitsong_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitline',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
