# Generated by Django 4.2 on 2023-11-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0006_alter_splitline_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitreportpayment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
