# Generated by Django 4.2 on 2023-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSplitSong',
            fields=[
                ('unique_id', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('split', models.FloatField()),
                ('amount', models.FloatField()),
                ('income', models.FloatField()),
                ('report_title', models.CharField(max_length=200)),
                ('distributionreport_id', models.IntegerField()),
                ('stakeholder_id', models.IntegerField()),
            ],
            options={
                'db_table': 'view_split_songs',
                'managed': False,
            },
        ),
    ]
