# Generated by Django 4.2 on 2023-12-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0006_stakeholder_payment_detail'),
        ('reports', '0008_distributionreport_payment_status'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('distributionreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.distributionreport')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder')),
            ],
        ),
    ]
