# Generated by Django 4.2 on 2023-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
