# Generated by Django 4.2 on 2023-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionreport',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
