# Generated by Django 4.2 on 2023-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_distributionreport_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionreport',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
