# Generated by Django 4.2 on 2023-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_distributionreport_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionreport',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionreport',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
