# Generated by Django 4.2 on 2023-11-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_distributionreport_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionreport',
            name='payment_status',
            field=models.CharField(choices=[('done', 'Concluído'), ('processing', 'Processando'), ('opened', 'Aberto')], default='opened'),
        ),
    ]
