# Generated by Django 4.2 on 2023-10-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyright', '0003_song_is_editor_alter_song_ecad'),
        ('split', '0004_rename_distributionreportpayment_splitreportpayment'),
        ('stakeholders', '0002_alter_contact_kind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Stakeholder',
        ),
    ]
