# Generated by Django 4.2 on 2023-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_stakeholder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='payment_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
