# Generated by Django 4.2 on 2023-09-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('ecad', models.CharField(max_length=20)),
                ('iswc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SongHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('author', 'Compsitor/Autor'), ('published', 'Editor')], max_length=30)),
                ('royalties_share', models.DecimalField(decimal_places=3, max_digits=5)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copyright.song')),
            ],
        ),
    ]
