# Generated by Django 4.2 on 2023-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyright', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='iswc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
