# Generated by Django 4.2 on 2023-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyright', '0002_alter_song_iswc'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_editor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='ecad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
